version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /packages/shared/pluggable-widgets-commons
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/tools/release-utils-internal
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/shared/charts
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /automation/run-e2e
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /automation/scripts
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/accessibility-helper-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/accordion-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/area-chart-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/badge-button-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/badge-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/bar-chart-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/barcode-scanner-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/bubble-chart-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/customWidgets/calendar-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/carousel-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/charts-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/color-picker-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/column-chart-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/modules/data-widgets
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/datagrid-date-filter-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/datagrid-dropdown-filter-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/datagrid-number-filter-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/datagrid-text-filter-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/datagrid-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/dropdown-sort-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/fieldset-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/gallery-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/heatmap-chart-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/html-element-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/image-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/language-selector-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/line-chart-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/maps-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/pie-doughnut-chart-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/popup-menu-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/progress-bar-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/progress-circle-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/range-slider-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/rating-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/rich-text-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/slider-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/switch-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/time-series-chart-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/timeline-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/tooltip-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/tree-node-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/pluggableWidgets/video-player-web
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /packages/modules/web-actions
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
