Atlas:
  - packages/**/*atlas*/**/*
documentation:
  - all: ["*.md"]
WebActions:
  - packages/*/web-actions/**/*
  - packages/*/nanoflow-actions-web/**/*
Charts:
  - packages/*/charts/**/*
  - packages/*/*-chart-web/**/*
DataGrid:
  - packages/*/data-widgets/**/*
  - packages/*/datagrid-*/**/*
  - packages/*/dropdown-sort-web/**/*
  - packages/*/gallery-web/**/*
  - packages/*/tree-node-web/**/*
Hybrid:
  - packages/jsActions/*-hybrid/**/*
PWA:
  - packages/**/barcode-scanner-web/**/*
  - packages/**/nanoflow-actions-web/**/*
test:
  - all: ["*.spec.*"]
