variables:
- name: projectName
  value: 'Mendix.Widgets.Datagrid-web'
- name: mpkName
  value: 'com.2gplus.widget.web.Datagrid.mpk'
- name: widgetFolder
  value: 'packages/pluggableWidgets/2G-datagrid-web'
variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
  
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Windows Build
    steps:
    - task: BuildServer@0
      displayName: 'Get version'
      inputs:
        buildServerServiceName: 'BuildServer 2G'
        buildServerProject: $(projectName)
        buildType: 'milestone'
        command: start
    - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      path: $(pnpm_config_cache)
    displayName: Cache pnpm

  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"

  - script: |
      pnpm install
      pnpm run build
    displayName: "pnpm install and build"
    - task: UseNode@1
      inputs:
        version: '18.x'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: 'install'
    - task: Npm@1
      displayName: 'Update build number'
      inputs:
        command: 'custom'
        workingDir: $(widgetFolder)
        customCommand: '--no-git-tag-version version $(Build.BuildNumber)'
    - task: Npm@1
      displayName: 'npm run build'
      inputs:
        command: 'custom'
        workingDir: $(widgetFolder)
        customCommand: 'run build'
    - task: BuildServer@0
      condition: failed()
      displayName: 'Abort version'
      inputs:
        buildServerServiceName: 'BuildServer 2G'
        buildServerProject: $(projectName)
        buildType: 'milestone'
        command: abort
    - task: BuildServer@0
      condition: succeeded()
      displayName: 'Commit version'
      inputs:
        buildServerServiceName: 'BuildServer 2G'
        buildServerProject: $(projectName)
        buildType: 'milestone'
        command: 'commit'
    - task: 2G-ProgetFeedUpload@0
      inputs:
        progetServiceName: '2G Proget'
        progetFeedName: 'upack/mendix-widgets'
        pathToPublish: '$(widgetFolder)/dist/$(Build.BuildNumber)/$(mpkName)'
        packageNameVersionRegex: '$(widgetFolder)\/dist\/(?<version>\d+.\d+.\d+)\/(?<name>.*).mpk'

