name: "Publishes a package to marketplace"

on:
  release:
    types: [published]

jobs:
  publish-new-version:
    name: "Publish a new package version from GitHub release"
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}

    steps:
      - name: Check release tag
        run: |
          match=$(node -p "(/^[a-z0-9-]+-v\d+\.\d+\.\d+$/m).exec('$TAG') ? 1 : -1")
          if [ $match -eq -1 ];
          then
            echo "::error::Invalid tag format."
            exit 1
          fi
      - name: "Set PACKAGE env var"
        run: echo "PACKAGE=${TAG%-v*}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 1
      - name: Setup pnpm
        uses: pnpm/action-setup@537643d491d20c2712d11533497cb47b2d0eb9d5 # v2.2.3
        with:
          version: ^7.13.4
      - name: Setup node
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # v3.5.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Search for package in workspace
        run: |
          if [[ -z "$(pnpm ls --json --filter=$PACKAGE)" ]];
          then
            echo "::error::Package $PACKAGE not found in workspace.";
            exit 1;
          fi
      - name: Run publish script
        run: pnpm run publish-marketplace --filter=$PACKAGE
        env:
          CPAPI_URL: ${{ secrets.CPAPI_URL }}
          CPAPI_USER: ${{ secrets.CPAPI_USER }}
          CPAPI_USER_OPENID: ${{ secrets.CPAPI_USER_OPENID }}
          CPAPI_PASS: ${{ secrets.CPAPI_PASS }}