name: Renovate

on:
  workflow_dispatch:

  schedule:
    # At minute 0 past hour 8, 14, and 20 on every day-of-week from Monday through Friday.
    - cron: '0 8,14,20 * * 1-5'

jobs:
  renovate:
    name: Run self-hosted Renovate
    runs-on:  ubuntu-latest
    if: >-
      ${{ contains(fromJson('["workflow_dispatch", "schedule"]'), github.event_name) ||
          github.event.label.name == 'renovate-rebase' }}
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0

      - name: Check SHA in GH Actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@21991cec25093947ff3f62e4c223df0260c39944 # v2.1.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@95cbcd7e8b9d0d69e15ba26208631839ce7eee48 # v36.0.2
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          useSlim: false
