name: Sandbox

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package name to release (name in package.json)"
        required: true

jobs:
  check:
    name: "Create widget/module release on GitHub"
    runs-on: ubuntu-latest
    env:
      PACKAGE: ${{ github.event.inputs.package }}

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 1
      - name: Setup pnpm
        uses: pnpm/action-setup@537643d491d20c2712d11533497cb47b2d0eb9d5 # v2.2.3
        with:
          version: ^7.13.4
      - name: Search for $PACKAGE in workspace
        run: >
          if [[ -z "$(pnpm ls --json --filter=$PACKAGE)" ]];
          then
            echo "::error::Package $PACKAGE not found in workspace.";
          fi